name: Branch & Commit Conventions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node (for commitlint)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Branch name lint
        uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          # Allowed prefixes separated by comma
          allowed_prefixes: 'feat,fix,chore,ci,docs,test,refactor,perf,security'
          regex: '^[a-z0-9][a-z0-9-_/]*$'
          max_length: 60
          min_length: 6

      - name: Commitlint (Conventional Commits)
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json
